name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: avanochi/web-app/avanochi-frontend/package-lock.json

    - name: Install dependencies
      run: |
        cd avanochi/web-app/avanochi-frontend
        npm ci

    - name: Build Angular app
      run: |
        cd avanochi/web-app/avanochi-frontend
        npm run build -- --base-href="/AVANOCHI/"

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './avanochi/web-app/avanochi-frontend/dist/avanochi-frontend'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4